# Values used for the deployed application.
service:
  name: delivery-varnish
  # Apply the certificate from content test by default
  certificateAwsArn: "arn:aws:acm:eu-west-1:070529446553:certificate/a6ab3d87-cdae-4db4-838f-3dbce570ad47"

elb:
  tags: "systemCode=upp,teamDL=universal.publishing.platform@ft.com,environment=d"

s3:
  enabled: "false"
