# Values used for the deployed application.
service:
  name: delivery-varnish
  certificateAwsArn: "arn:aws:acm:eu-west-1:469211898354:certificate/c9fc4ada-63ee-4951-b1ea-429ba586cbf7"

elb:
  tags: "systemCode=upp,teamDL=universal.publishing.platform@ft.com,environment=p"

s3:
  bucketName: "content-prod-elb-access-logs-eu-west-1"
  prefix: "upp-prod-delivery-eu/delivery-varnish"
  enabled: "true"
  interval: "5"
