---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.service.name }}-elb-registrator-job-{{ .Release.Revision}}"
  # This is what defines this resource as a hook. Without this line, the
  # job is considered part of the release.
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  template:
    metadata:
      name: "{{ .Values.service.name }}-elb-registrator"
    spec:
      # Keep trying to register in DNS until we manage to do it
      restartPolicy: OnFailure
      containers:
      - name: "{{ .Values.service.name }}-elb-registrator"
        image: "{{ .Values.elbRegistrator.image }}"
        volumeMounts:
        #We need the certificates for being able to make the DynDNS http call
        - mountPath: /etc/ssl/certs
          name: certificates-storage
        env:
        - name: DOMAINS
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: dns_subdomain
        - name: DomainZone
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: dns_zone
        - name: KONSTRUCTOR_API_KEY
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: kon.dns_api.key
        - name: K8S_LB_SERVICE
          value: "{{ .Values.service.name }}"
        - name: K8S_LB_SERVICE_NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: k8s.app_namespace
      volumes:
      - name: certificates-storage
        hostPath:
          path: /usr/share/ca-certificates
